spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vodafone-fis
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: 
              memory: 
            limits:
              cpu: 
              memory: 512Mi
          env:
          - name: FTP_SERVICE_NAME
            value: external-ftp-service
          - name: FTP_SERVICE_USERNAME
            value: vodafone
          - name: FTP_SERVICE_PASSWORD
            value: password
          - name: JAVA_DIAGNOSTICS
            value: true
